### ISSUE TITLE
"forum.get_board" endpoint

### ISSUE THREAD

**Issue by teistiz** [katajakasa/aetherguild2#4]
The forum front-end could use a way to fetch a single board by id and get both board information and users/threads (like what the 'forum.get_threads' route already does).

Without something like this, the forum needs to fetch all boards and then store them somewhere for single-board thread listing views. This doesn't fit into the application's structure very well when the board is used as a top-level React Router view component.

**Comment by katajakasa** [comment]
Done. get_threads, get_posts, get_post now return additional information.
